### ISSUE TITLE
Checklist με ρυθμίσεις του drupal για χρήση webforms

### ISSUE THREAD

**Issue by plirof2** [itminedu/forms_minedu#11]
Η παρακάτω λίστα σκοπό έχει να αποτελέσει την checklist για το στήσιμο ένός σύστήματος Forms
# Εγκατάσταση:
- [ ] Drupal 7
- [ ] module Views
- [ ] module Chaos Tools
- [ ] module Webforms 7.x-4.14
- [ ] module Webform Participants
- [ ] module Webforms Multiple :  WfM 7.x-1.x-dev
- [ ] module Webform authcode   7.x-1.1 
- [ ] module Simple Mail    7.x-1.1
- [ ] module Token  7.x-1.6
- [ ] module Localization update    7.x-2.0
- [ ] module Node export    7.x-3.1 (για να μπορόυμε να εξάγουμε/εισάγουμε και να αποθηκεύουμε τις φόρμες που δημιουργούμε)
- [ ] module UUID  (Απαιτείται από: Node export)
- [ ] CAS   7.x-1.5 Central Authentication Service
- [ ] theme ???
# Παραμετροποίηση:
### Menu Modules :  πρέπει να είναι ενεργοποίημένα τα :
- [ ] Chaos tool suite/Chaos tools  
- [ ] Views/Views
- [ ] Views/Views UI
- [ ] Webform/Webform **\* Κυρίως plugin
- [ ] Webform/Webform Participants -Δημιουργία invitation codes
- [ ] Webform/Webform Multiple - Loop answers support
- [ ] Webform/Webform authcode - Master password (?)
- [ ] Άλλο/Simple Mail (απαραίτητο από Webform Participants )
- [ ] Άλλο/Token 
- [ ] UUID/Universally Unique ID
- [ ] Node export/Node export (εξαγωγή/εισαγωγη form)  
- [ ] Πολύγλωσσο/Localization update 
- [ ] Central Authentication Service/CAS
### Ρυθμίσεις drupal
- [ ] Δημιουργία group "minedu_editors" ή "minedu_eishgites"
- [ ] Δικαίωμα view own webform results στον ρόλο "minedu_editors"
### Ρυθμίσεις συγκεκριμένες που θέλουν τα mobules
- [ ] Webforms : 
### Menu Modules core:  πρέπει να είναι ενεργοποίημένα τα :
- [ ] Comment
- [ ] Color
- [ ] Block (Απαιτείται από: Dashboard)
- [ ] Dashboard
- [ ] Contextual links
- [ ] Database logging
- [ ] Field UI
- [ ] Help
- [ ] List
- [ ] Number
- [ ] Overlay (απαραίτητο μάλλον - δείχνει με overlay τα μενου - να δοκιμάσουμε αν μπορούμε να δουλέψουμε χωρίς αυτό)
- [ ] Path  7.50    Επιτρέπει στους χρήστες να μετονομάζουν διευθύνσεις URL.
- [ ] RDF
- [ ] Search
- [ ] Shortcut
- [ ] Toolbar 
- [ ] Update manager
