### ISSUE TITLE
checklist Αλλαγές στο theme (και σε άλλα θέματα εμφάνισης)- για την εφαρμογή "μόρια" 

### ISSUE THREAD

**Issue by plirof2** [itminedu/forms_minedu#13]
**CAS login/logout :**
- [x] My Baltic: απενεργοποίηση "Δευτερεύον μενού " για να μην φαίνεται το "αποσύνδεση"(αφού βάλαμε κουμπί/μπλοκ caslogout" http://forms1.minedu.gov.gr/test/admin/appearance/settings/my_bartik 
- [x] Δημιουργία νέου μπλοκ στην `κεφαλίδα` με τον κωδικα που δημιουργεί κουμπι με λινκ στο "/caslogout" και να φαίνεται ΜΟΝΟ στον ρόλο "registered users"
- [x] Block > user menu (edit) > Disable "my account - ο λογαριασμός μου"` /#overlay=admin/structure/menu/manage/user-menu`
- [x] Αρχική » Διαχείριση » Δομή : CAS login , login/Είσοδος -> κεφαλίδα
- [x] CAS settings >Login/Logout Destinations>Logout destination > βάλε `<front>` http://forms1.minedu.gov.gr/test/#overlay=admin/config/people/cas

- [x] Block > user menu, CAS login , login : να μπει στην "κεφαλίδα"
- [x] Block > Το "Είσοδος" login : να μπει στην "πρώτη πλαινή στήλη" και να είναι ορατό μόνο στο path `/hiddenlogin`
- [ ] Παραμετροποίηση : CAS login : Make CAS login default on login forms 
- [x] Αρχική » Διαχείριση » Παραμετροποίηση » Χρήστες -> Ποιος μπορεί να κάνει εγγραφή για λογαριασμό;   Διαχειριστές μόνο **(να γίνει έλεγχος εαν οι νέοι χρήστες/υπηρεσίες μπορούν να κάνουν login μέσω CAS κανονικά) - OK checked**

- [x] Παραμετροποίηση : http://forms1.minedu.gov.gr/test/admin/people/permissions απενεργοποίηση των δικαιωμάτων "Προβολή δημοσιευμένου περιεχομένου"  από τον "ανώνυμο χρήστη" 
- [ ] Παραμετροποίηση : http://forms1.minedu.gov.gr/test/admin/people/permissions απενεργοποίηση των δικαιωμάτων "Προβολή δημοσιευμένου περιεχομένου"  από τον "πιστοποιημένος χρήστης" και από ΔΙΕΥΘΥΝΣΗ ΔΕ - ΔIΔΕ	ΔΙΕΥΘΥΝΣΗ ΠΕ - ΔIΠΕ	ΠΕΡΙΦΕΡΕΙΑΚΗ ΔΙΕΥΘΥΝΣΗ ΕΚΠΑΙΔΕΥΣΗΣ - ΠΔΕ (ΝΑ ΔΟΚΙΜΑΣΤΕΙ μήπως επιτρέπει ΜΟΝΟ μέσω editable views τις αλλαγές

**Comment by plirof2** [comment]
Δημιουργία νέου μπλοκ στην κεφαλίδα με τον κωδικα που δημιουργεί κουμπι με λινκ στο "/caslogout" 
titlos: cas_logout_psd
Ενεργοποίηση του PHPcode στο φιλτρο και γράψτε:
κώδικας για forma.minedu.gov.gr (προσοχή στο /caslogout)

```
<form action="/caslogout">
    <p class="rtecenter"><input type="submit" value="Εξοδος από ΠΣΔ" /></p>
</form>
```

Εαν η σελίδα βρίσκεται σε φάκελο του server:
κώδικας για forma1.minedu.gov.gr/test/

```
<form action="/test/caslogout">
    <p class="rtecenter"><input type="submit" value="Εξοδος από ΠΣΔ" /></p>
</form>
```
